package com.hm.schwab.clientinterface.streaming;

public enum Service {
	LEVELONE_EQUITIES,
	LEVELONE_OPTIONS,
	LEVELONE_FUTURES,
	LEVELONE_FUTURES_OPTIONS,
	LEVELONE_FOREX,
	NYSE_BOOK,
	NASDAQ_BOOK,
	OPTIONS_BOOK,
	CHART_EQUITY,
	CHART_FUTURES,
	SCREENER_EQUITY,
	SCREENER_OPTION,
	ACCT_ACTIVITY
}
